name: _base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - git=2.41.0
  - exa=0.10.1
  - bat=0.23.0
  - curl=8.2.1
  - tar=1.34
  - zip=3.0
  - zsh=5.8
  - starship=1.16.0
  - ffmpeg=6.0.0
  - python=3.9.16
  - pip=23.2.1
  - pytorch-cpu=2.0.0
  - torchvision=0.15.2
  - rich-cli=1.8.0
  - gdown=4.7.1
  - tensorboard=2.13.0
