#!/usr/bin/env python

import pyotp
import sys
import os.path
import argparse


parser = argparse.ArgumentParser()
parser.add_argument('--duo-path', type=str, default='~/.duo')
parser.add_argument('--profile', type=str, default='brown')
args = parser.parse_args()

file_token = os.path.join(
    os.path.expanduser(args.duo_path),
    f'{args.profile}.hotp'
)

f = open(file_token, "r+")
secret = f.readline()[0:-1]
offset = f.tell()
count = int(f.readline())

hotp = pyotp.HOTP(secret)
print(hotp.at(count))

f.seek(offset)
f.write(str(count + 1))
f.close()
